/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpotifyLoginRouteImport } from './routes/spotify/login'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyLoginRoute = SpotifyLoginRouteImport.update({
  id: '/spotify/login',
  path: '/spotify/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify/callback',
  path: '/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/spotify/login': typeof SpotifyLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/spotify/login': typeof SpotifyLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/spotify/login': typeof SpotifyLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spotify/callback' | '/spotify/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spotify/callback' | '/spotify/login'
  id: '__root__' | '/' | '/spotify/callback' | '/spotify/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
  SpotifyLoginRoute: typeof SpotifyLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify/login': {
      id: '/spotify/login'
      path: '/spotify/login'
      fullPath: '/spotify/login'
      preLoaderRoute: typeof SpotifyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify/callback': {
      id: '/spotify/callback'
      path: '/spotify/callback'
      fullPath: '/spotify/callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
  SpotifyLoginRoute: SpotifyLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
